#ifndef SIMPLE_CACHE_DEFS_H
#define SIMPLE_CACHE_DEFS_H

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// This file is distributed as part of the Cache Replacement Championship     //
// workshop held in conjunction with ISCA'2010.                               //
//                                                                            //
//                                                                            //
// Everyone is granted permission to copy, modify, and/or re-distribute       //
// this software.                                                             //
//                                                                            //
// Please contact Aamer Jaleel <ajaleel@gmail.com> should you have any        //
// questions                                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

// --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE ---
// --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE ---
// --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE --- DO NOT EDIT THIS FILE ---

// IMPORTANT NOTE: DO NOT CHANGE ANYTHING IN THIS HEADER FILE. Changing anything
// in here will violate the competition rules.

// ASIM core
#include "asim-defs.h"

typedef UINT64 Addr_t;
typedef UINT64 BITVECTOR;
typedef UINT64 COUNTER;

typedef enum
{
    EVICTED = 0,
    PENDING_EVICT = 0,
    READY = 0
} EvictState;

typedef struct
{
    Addr_t      tag;         // Tag of line
    bool        valid;       // Is line valid?
    bool        exclusive;   // Is line exclusive?
    bool        dirty;       // Is line dirty?
    bool        shared_upgrading; // Is line in process of begin upgraded from shared to exclusive?
    EvictState evict_state;
  //    BITVECTOR   sharing_dir; // Directory of which core accessed this line
} LINE_STATE;

typedef enum 
{
    ACCESS_IFETCH      = 0,
    ACCESS_LOAD        = 1,
    ACCESS_STORE       = 2,
    ACCESS_INSPECT     = 3,
    ACCESS_UNSUPPORT1  = 4,
    ACCESS_PREFETCH    = 5,
    ACCESS_WRITEBACK   = 6,
    ACCESS_RFO         = 7,
    ACCESS_UPGRADE     = 8,
    ACCESS_SNOOP       = 9,
    ACCESS_MAX         = 10
} AccessTypes;

#define IS_STORE(X)  (X == ACCESS_STORE || X == ACCESS_WRITEBACK)

#endif
